// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
#if UNITY_IOS
using System.Runtime.InteropServices;
#endif
namespace UYMO
{
    public class ChannelImpl
    {
#if UNITY_IOS && !UNITY_EDITOR
		[DllImport("__Internal")]
		public static extern string GetChannelName();
        [DllImport("__Internal")]
		public static extern string GetVersion();
		[DllImport("__Internal")]
        public static extern void RestartApp();
        [DllImport("__Internal")]
		public static extern int GetVersionCode();
        [DllImport("__Internal")]
        public static extern string GetSDKControlFunc();
        [DllImport("__Internal")]
        public static extern void CallFunc(string funcID,string jsonArgs);
		public static void Exit(){ }
        public static string osName { get { return "ios"; } }

#elif UNITY_ANDROID && !UNITY_EDITOR

		static string _Channel;
		public static string GetChannelName()
		{
			try
			{
				if(_Channel == null )
				{
					_Channel = channel.CallStatic<string>("GetName");
				}
			}
			catch
			{
				_Channel = "uye_hl";
			}
			return _Channel;
        }

        public static string GetVersion()
        {
            return Application.version;
        }

        public static int GetVersionCode()
        {
            try
            {
                AndroidJavaClass jc = new AndroidJavaClass("com.uye.bugly.Bugly");
                return jc.CallStatic<int>("GetVersionCode");
            }
            catch
            {
                return 0;
            }
        }
        public static string osName { get { return "android"; } }
        public static void RestartApp()
        {
            try
            {
			    channel.CallStatic("ResatrtApp");
            }
            catch
            {
                Debug.Log("Not support restart!");
            }
        }

        public static void Exit()
        {
            try
            {
                channel.CallStatic("Exit");
            }
            catch
            {
                Debug.Log("Not support Exit!");
            }
        }


        static AndroidJavaClass _ChannalCls;
        static AndroidJavaClass channel
        {
            get
            {
                if(_ChannalCls == null)
                {
                    _ChannalCls = new AndroidJavaClass("com.uye.channel.Channel");
                }
                return _ChannalCls;
            }
        }
        
        static string _SDKControlFuncJson = null;
        public static string GetSDKControlFunc()
        {
            try
            {
                _SDKControlFuncJson = channel.CallStatic<string>("GetSDKControlFunc");
            }
            catch
            {
                Debug.Log("请求SDK功能列表失败！");
            }
            return _SDKControlFuncJson;
        }

        public static void CallFunc(string funcID,string jsonArgs)
        {
            try
            {
                channel.CallStatic("CallFunc", funcID, jsonArgs);
            }
            catch(Exception e)
            {
                Debug.LogFormat("Not support CallFunc! {0}", e);
            }
        }

#else
        public static string GetChannelName()
        {
            return "uye_hl";
        }

        public static string GetVersion()
        {
#if UNITY_STANDALONE_OSX || UNITY_IOS
            return "0.0.1";
#else
            return Application.version;
#endif
        }
        public static int GetVersionCode()
        {
            return int.MaxValue;
        }
        public static string osName { get { return "windows"; } }
        public static void RestartApp()
        {
            Debug.Log("重启应用...");
            Application.Quit();
        }
        public static void Exit()
        {
            Debug.Log("Channel SDK Exit");
        }

        /// <summary>
        /// 查询由SDK实现的功能列表
        /// </summary>
        /// <returns></returns>
        public static string GetSDKControlFunc()
        {
            return null;
        }

        public static void CallFunc(string funcID, string jsonArgs)
        {
        }
#endif
    }
}

