// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HorsesMessage.proto

#ifndef PROTOBUF_HorsesMessage_2eproto__INCLUDED
#define PROTOBUF_HorsesMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "InnerMessage.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_HorsesMessage_2eproto();
void protobuf_AssignDesc_HorsesMessage_2eproto();
void protobuf_ShutdownFile_HorsesMessage_2eproto();

class GCBackHorseData;
class CGChoseHorse;
class GCChoseHorseBack;
class CGUseHorse;
class GCUseHorseBack;
class CGCultureToUpStar;
class GCCultureToUpStarBack;
class CGLookHorse;
class GCLookHorseBack;
class GCGetNewHorse;

// ===================================================================

class GCBackHorseData : public ::google::protobuf::Message {
 public:
  GCBackHorseData();
  virtual ~GCBackHorseData();

  GCBackHorseData(const GCBackHorseData& from);

  inline GCBackHorseData& operator=(const GCBackHorseData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GCBackHorseData& default_instance();

  void Swap(GCBackHorseData* other);

  // implements Message ----------------------------------------------

  GCBackHorseData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GCBackHorseData& from);
  void MergeFrom(const GCBackHorseData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .HorseInfo horseInfo = 1;
  inline int horseinfo_size() const;
  inline void clear_horseinfo();
  static const int kHorseInfoFieldNumber = 1;
  inline const ::HorseInfo& horseinfo(int index) const;
  inline ::HorseInfo* mutable_horseinfo(int index);
  inline ::HorseInfo* add_horseinfo();
  inline const ::google::protobuf::RepeatedPtrField< ::HorseInfo >&
      horseinfo() const;
  inline ::google::protobuf::RepeatedPtrField< ::HorseInfo >*
      mutable_horseinfo();

  // @@protoc_insertion_point(class_scope:GCBackHorseData)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::HorseInfo > horseinfo_;
  friend void  protobuf_AddDesc_HorsesMessage_2eproto();
  friend void protobuf_AssignDesc_HorsesMessage_2eproto();
  friend void protobuf_ShutdownFile_HorsesMessage_2eproto();

  void InitAsDefaultInstance();
  static GCBackHorseData* default_instance_;
};
// -------------------------------------------------------------------

class CGChoseHorse : public ::google::protobuf::Message {
 public:
  CGChoseHorse();
  virtual ~CGChoseHorse();

  CGChoseHorse(const CGChoseHorse& from);

  inline CGChoseHorse& operator=(const CGChoseHorse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CGChoseHorse& default_instance();

  void Swap(CGChoseHorse* other);

  // implements Message ----------------------------------------------

  CGChoseHorse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CGChoseHorse& from);
  void MergeFrom(const CGChoseHorse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 horseid = 1;
  inline bool has_horseid() const;
  inline void clear_horseid();
  static const int kHorseidFieldNumber = 1;
  inline ::google::protobuf::int64 horseid() const;
  inline void set_horseid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:CGChoseHorse)
 private:
  inline void set_has_horseid();
  inline void clear_has_horseid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 horseid_;
  friend void  protobuf_AddDesc_HorsesMessage_2eproto();
  friend void protobuf_AssignDesc_HorsesMessage_2eproto();
  friend void protobuf_ShutdownFile_HorsesMessage_2eproto();

  void InitAsDefaultInstance();
  static CGChoseHorse* default_instance_;
};
// -------------------------------------------------------------------

class GCChoseHorseBack : public ::google::protobuf::Message {
 public:
  GCChoseHorseBack();
  virtual ~GCChoseHorseBack();

  GCChoseHorseBack(const GCChoseHorseBack& from);

  inline GCChoseHorseBack& operator=(const GCChoseHorseBack& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GCChoseHorseBack& default_instance();

  void Swap(GCChoseHorseBack* other);

  // implements Message ----------------------------------------------

  GCChoseHorseBack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GCChoseHorseBack& from);
  void MergeFrom(const GCChoseHorseBack& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 flag = 1;
  inline bool has_flag() const;
  inline void clear_flag();
  static const int kFlagFieldNumber = 1;
  inline ::google::protobuf::int32 flag() const;
  inline void set_flag(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GCChoseHorseBack)
 private:
  inline void set_has_flag();
  inline void clear_has_flag();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 flag_;
  friend void  protobuf_AddDesc_HorsesMessage_2eproto();
  friend void protobuf_AssignDesc_HorsesMessage_2eproto();
  friend void protobuf_ShutdownFile_HorsesMessage_2eproto();

  void InitAsDefaultInstance();
  static GCChoseHorseBack* default_instance_;
};
// -------------------------------------------------------------------

class CGUseHorse : public ::google::protobuf::Message {
 public:
  CGUseHorse();
  virtual ~CGUseHorse();

  CGUseHorse(const CGUseHorse& from);

  inline CGUseHorse& operator=(const CGUseHorse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CGUseHorse& default_instance();

  void Swap(CGUseHorse* other);

  // implements Message ----------------------------------------------

  CGUseHorse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CGUseHorse& from);
  void MergeFrom(const CGUseHorse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 useflag = 1;
  inline bool has_useflag() const;
  inline void clear_useflag();
  static const int kUseflagFieldNumber = 1;
  inline ::google::protobuf::int32 useflag() const;
  inline void set_useflag(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CGUseHorse)
 private:
  inline void set_has_useflag();
  inline void clear_has_useflag();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 useflag_;
  friend void  protobuf_AddDesc_HorsesMessage_2eproto();
  friend void protobuf_AssignDesc_HorsesMessage_2eproto();
  friend void protobuf_ShutdownFile_HorsesMessage_2eproto();

  void InitAsDefaultInstance();
  static CGUseHorse* default_instance_;
};
// -------------------------------------------------------------------

class GCUseHorseBack : public ::google::protobuf::Message {
 public:
  GCUseHorseBack();
  virtual ~GCUseHorseBack();

  GCUseHorseBack(const GCUseHorseBack& from);

  inline GCUseHorseBack& operator=(const GCUseHorseBack& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GCUseHorseBack& default_instance();

  void Swap(GCUseHorseBack* other);

  // implements Message ----------------------------------------------

  GCUseHorseBack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GCUseHorseBack& from);
  void MergeFrom(const GCUseHorseBack& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 guid = 1;
  inline bool has_guid() const;
  inline void clear_guid();
  static const int kGuidFieldNumber = 1;
  inline ::google::protobuf::int64 guid() const;
  inline void set_guid(::google::protobuf::int64 value);

  // optional int32 useflag = 2;
  inline bool has_useflag() const;
  inline void clear_useflag();
  static const int kUseflagFieldNumber = 2;
  inline ::google::protobuf::int32 useflag() const;
  inline void set_useflag(::google::protobuf::int32 value);

  // optional int32 flag = 3;
  inline bool has_flag() const;
  inline void clear_flag();
  static const int kFlagFieldNumber = 3;
  inline ::google::protobuf::int32 flag() const;
  inline void set_flag(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GCUseHorseBack)
 private:
  inline void set_has_guid();
  inline void clear_has_guid();
  inline void set_has_useflag();
  inline void clear_has_useflag();
  inline void set_has_flag();
  inline void clear_has_flag();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 guid_;
  ::google::protobuf::int32 useflag_;
  ::google::protobuf::int32 flag_;
  friend void  protobuf_AddDesc_HorsesMessage_2eproto();
  friend void protobuf_AssignDesc_HorsesMessage_2eproto();
  friend void protobuf_ShutdownFile_HorsesMessage_2eproto();

  void InitAsDefaultInstance();
  static GCUseHorseBack* default_instance_;
};
// -------------------------------------------------------------------

class CGCultureToUpStar : public ::google::protobuf::Message {
 public:
  CGCultureToUpStar();
  virtual ~CGCultureToUpStar();

  CGCultureToUpStar(const CGCultureToUpStar& from);

  inline CGCultureToUpStar& operator=(const CGCultureToUpStar& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CGCultureToUpStar& default_instance();

  void Swap(CGCultureToUpStar* other);

  // implements Message ----------------------------------------------

  CGCultureToUpStar* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CGCultureToUpStar& from);
  void MergeFrom(const CGCultureToUpStar& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 horseid = 1;
  inline bool has_horseid() const;
  inline void clear_horseid();
  static const int kHorseidFieldNumber = 1;
  inline ::google::protobuf::int64 horseid() const;
  inline void set_horseid(::google::protobuf::int64 value);

  // optional int32 usegemflag = 2;
  inline bool has_usegemflag() const;
  inline void clear_usegemflag();
  static const int kUsegemflagFieldNumber = 2;
  inline ::google::protobuf::int32 usegemflag() const;
  inline void set_usegemflag(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CGCultureToUpStar)
 private:
  inline void set_has_horseid();
  inline void clear_has_horseid();
  inline void set_has_usegemflag();
  inline void clear_has_usegemflag();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 horseid_;
  ::google::protobuf::int32 usegemflag_;
  friend void  protobuf_AddDesc_HorsesMessage_2eproto();
  friend void protobuf_AssignDesc_HorsesMessage_2eproto();
  friend void protobuf_ShutdownFile_HorsesMessage_2eproto();

  void InitAsDefaultInstance();
  static CGCultureToUpStar* default_instance_;
};
// -------------------------------------------------------------------

class GCCultureToUpStarBack : public ::google::protobuf::Message {
 public:
  GCCultureToUpStarBack();
  virtual ~GCCultureToUpStarBack();

  GCCultureToUpStarBack(const GCCultureToUpStarBack& from);

  inline GCCultureToUpStarBack& operator=(const GCCultureToUpStarBack& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GCCultureToUpStarBack& default_instance();

  void Swap(GCCultureToUpStarBack* other);

  // implements Message ----------------------------------------------

  GCCultureToUpStarBack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GCCultureToUpStarBack& from);
  void MergeFrom(const GCCultureToUpStarBack& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 flag = 1;
  inline bool has_flag() const;
  inline void clear_flag();
  static const int kFlagFieldNumber = 1;
  inline ::google::protobuf::int32 flag() const;
  inline void set_flag(::google::protobuf::int32 value);

  // optional int32 luckflag = 2;
  inline bool has_luckflag() const;
  inline void clear_luckflag();
  static const int kLuckflagFieldNumber = 2;
  inline ::google::protobuf::int32 luckflag() const;
  inline void set_luckflag(::google::protobuf::int32 value);

  // optional .HorseInfo horseInfo = 3;
  inline bool has_horseinfo() const;
  inline void clear_horseinfo();
  static const int kHorseInfoFieldNumber = 3;
  inline const ::HorseInfo& horseinfo() const;
  inline ::HorseInfo* mutable_horseinfo();
  inline ::HorseInfo* release_horseinfo();
  inline void set_allocated_horseinfo(::HorseInfo* horseinfo);

  // optional .HorseInfo newhorseInfo = 4;
  inline bool has_newhorseinfo() const;
  inline void clear_newhorseinfo();
  static const int kNewhorseInfoFieldNumber = 4;
  inline const ::HorseInfo& newhorseinfo() const;
  inline ::HorseInfo* mutable_newhorseinfo();
  inline ::HorseInfo* release_newhorseinfo();
  inline void set_allocated_newhorseinfo(::HorseInfo* newhorseinfo);

  // @@protoc_insertion_point(class_scope:GCCultureToUpStarBack)
 private:
  inline void set_has_flag();
  inline void clear_has_flag();
  inline void set_has_luckflag();
  inline void clear_has_luckflag();
  inline void set_has_horseinfo();
  inline void clear_has_horseinfo();
  inline void set_has_newhorseinfo();
  inline void clear_has_newhorseinfo();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 flag_;
  ::google::protobuf::int32 luckflag_;
  ::HorseInfo* horseinfo_;
  ::HorseInfo* newhorseinfo_;
  friend void  protobuf_AddDesc_HorsesMessage_2eproto();
  friend void protobuf_AssignDesc_HorsesMessage_2eproto();
  friend void protobuf_ShutdownFile_HorsesMessage_2eproto();

  void InitAsDefaultInstance();
  static GCCultureToUpStarBack* default_instance_;
};
// -------------------------------------------------------------------

class CGLookHorse : public ::google::protobuf::Message {
 public:
  CGLookHorse();
  virtual ~CGLookHorse();

  CGLookHorse(const CGLookHorse& from);

  inline CGLookHorse& operator=(const CGLookHorse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CGLookHorse& default_instance();

  void Swap(CGLookHorse* other);

  // implements Message ----------------------------------------------

  CGLookHorse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CGLookHorse& from);
  void MergeFrom(const CGLookHorse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 playerUid = 1;
  inline bool has_playeruid() const;
  inline void clear_playeruid();
  static const int kPlayerUidFieldNumber = 1;
  inline ::google::protobuf::int64 playeruid() const;
  inline void set_playeruid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:CGLookHorse)
 private:
  inline void set_has_playeruid();
  inline void clear_has_playeruid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 playeruid_;
  friend void  protobuf_AddDesc_HorsesMessage_2eproto();
  friend void protobuf_AssignDesc_HorsesMessage_2eproto();
  friend void protobuf_ShutdownFile_HorsesMessage_2eproto();

  void InitAsDefaultInstance();
  static CGLookHorse* default_instance_;
};
// -------------------------------------------------------------------

class GCLookHorseBack : public ::google::protobuf::Message {
 public:
  GCLookHorseBack();
  virtual ~GCLookHorseBack();

  GCLookHorseBack(const GCLookHorseBack& from);

  inline GCLookHorseBack& operator=(const GCLookHorseBack& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GCLookHorseBack& default_instance();

  void Swap(GCLookHorseBack* other);

  // implements Message ----------------------------------------------

  GCLookHorseBack* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GCLookHorseBack& from);
  void MergeFrom(const GCLookHorseBack& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 flag = 1;
  inline bool has_flag() const;
  inline void clear_flag();
  static const int kFlagFieldNumber = 1;
  inline ::google::protobuf::int32 flag() const;
  inline void set_flag(::google::protobuf::int32 value);

  // optional int32 horseId = 2;
  inline bool has_horseid() const;
  inline void clear_horseid();
  static const int kHorseIdFieldNumber = 2;
  inline ::google::protobuf::int32 horseid() const;
  inline void set_horseid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GCLookHorseBack)
 private:
  inline void set_has_flag();
  inline void clear_has_flag();
  inline void set_has_horseid();
  inline void clear_has_horseid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 flag_;
  ::google::protobuf::int32 horseid_;
  friend void  protobuf_AddDesc_HorsesMessage_2eproto();
  friend void protobuf_AssignDesc_HorsesMessage_2eproto();
  friend void protobuf_ShutdownFile_HorsesMessage_2eproto();

  void InitAsDefaultInstance();
  static GCLookHorseBack* default_instance_;
};
// -------------------------------------------------------------------

class GCGetNewHorse : public ::google::protobuf::Message {
 public:
  GCGetNewHorse();
  virtual ~GCGetNewHorse();

  GCGetNewHorse(const GCGetNewHorse& from);

  inline GCGetNewHorse& operator=(const GCGetNewHorse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GCGetNewHorse& default_instance();

  void Swap(GCGetNewHorse* other);

  // implements Message ----------------------------------------------

  GCGetNewHorse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GCGetNewHorse& from);
  void MergeFrom(const GCGetNewHorse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 horseId = 1;
  inline bool has_horseid() const;
  inline void clear_horseid();
  static const int kHorseIdFieldNumber = 1;
  inline ::google::protobuf::int32 horseid() const;
  inline void set_horseid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GCGetNewHorse)
 private:
  inline void set_has_horseid();
  inline void clear_has_horseid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 horseid_;
  friend void  protobuf_AddDesc_HorsesMessage_2eproto();
  friend void protobuf_AssignDesc_HorsesMessage_2eproto();
  friend void protobuf_ShutdownFile_HorsesMessage_2eproto();

  void InitAsDefaultInstance();
  static GCGetNewHorse* default_instance_;
};
// ===================================================================


// ===================================================================

// GCBackHorseData

// repeated .HorseInfo horseInfo = 1;
inline int GCBackHorseData::horseinfo_size() const {
  return horseinfo_.size();
}
inline void GCBackHorseData::clear_horseinfo() {
  horseinfo_.Clear();
}
inline const ::HorseInfo& GCBackHorseData::horseinfo(int index) const {
  // @@protoc_insertion_point(field_get:GCBackHorseData.horseInfo)
  return horseinfo_.Get(index);
}
inline ::HorseInfo* GCBackHorseData::mutable_horseinfo(int index) {
  // @@protoc_insertion_point(field_mutable:GCBackHorseData.horseInfo)
  return horseinfo_.Mutable(index);
}
inline ::HorseInfo* GCBackHorseData::add_horseinfo() {
  // @@protoc_insertion_point(field_add:GCBackHorseData.horseInfo)
  return horseinfo_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::HorseInfo >&
GCBackHorseData::horseinfo() const {
  // @@protoc_insertion_point(field_list:GCBackHorseData.horseInfo)
  return horseinfo_;
}
inline ::google::protobuf::RepeatedPtrField< ::HorseInfo >*
GCBackHorseData::mutable_horseinfo() {
  // @@protoc_insertion_point(field_mutable_list:GCBackHorseData.horseInfo)
  return &horseinfo_;
}

// -------------------------------------------------------------------

// CGChoseHorse

// optional int64 horseid = 1;
inline bool CGChoseHorse::has_horseid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CGChoseHorse::set_has_horseid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CGChoseHorse::clear_has_horseid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CGChoseHorse::clear_horseid() {
  horseid_ = GOOGLE_LONGLONG(0);
  clear_has_horseid();
}
inline ::google::protobuf::int64 CGChoseHorse::horseid() const {
  // @@protoc_insertion_point(field_get:CGChoseHorse.horseid)
  return horseid_;
}
inline void CGChoseHorse::set_horseid(::google::protobuf::int64 value) {
  set_has_horseid();
  horseid_ = value;
  // @@protoc_insertion_point(field_set:CGChoseHorse.horseid)
}

// -------------------------------------------------------------------

// GCChoseHorseBack

// optional int32 flag = 1;
inline bool GCChoseHorseBack::has_flag() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GCChoseHorseBack::set_has_flag() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GCChoseHorseBack::clear_has_flag() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GCChoseHorseBack::clear_flag() {
  flag_ = 0;
  clear_has_flag();
}
inline ::google::protobuf::int32 GCChoseHorseBack::flag() const {
  // @@protoc_insertion_point(field_get:GCChoseHorseBack.flag)
  return flag_;
}
inline void GCChoseHorseBack::set_flag(::google::protobuf::int32 value) {
  set_has_flag();
  flag_ = value;
  // @@protoc_insertion_point(field_set:GCChoseHorseBack.flag)
}

// -------------------------------------------------------------------

// CGUseHorse

// optional int32 useflag = 1;
inline bool CGUseHorse::has_useflag() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CGUseHorse::set_has_useflag() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CGUseHorse::clear_has_useflag() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CGUseHorse::clear_useflag() {
  useflag_ = 0;
  clear_has_useflag();
}
inline ::google::protobuf::int32 CGUseHorse::useflag() const {
  // @@protoc_insertion_point(field_get:CGUseHorse.useflag)
  return useflag_;
}
inline void CGUseHorse::set_useflag(::google::protobuf::int32 value) {
  set_has_useflag();
  useflag_ = value;
  // @@protoc_insertion_point(field_set:CGUseHorse.useflag)
}

// -------------------------------------------------------------------

// GCUseHorseBack

// optional int64 guid = 1;
inline bool GCUseHorseBack::has_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GCUseHorseBack::set_has_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GCUseHorseBack::clear_has_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GCUseHorseBack::clear_guid() {
  guid_ = GOOGLE_LONGLONG(0);
  clear_has_guid();
}
inline ::google::protobuf::int64 GCUseHorseBack::guid() const {
  // @@protoc_insertion_point(field_get:GCUseHorseBack.guid)
  return guid_;
}
inline void GCUseHorseBack::set_guid(::google::protobuf::int64 value) {
  set_has_guid();
  guid_ = value;
  // @@protoc_insertion_point(field_set:GCUseHorseBack.guid)
}

// optional int32 useflag = 2;
inline bool GCUseHorseBack::has_useflag() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GCUseHorseBack::set_has_useflag() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GCUseHorseBack::clear_has_useflag() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GCUseHorseBack::clear_useflag() {
  useflag_ = 0;
  clear_has_useflag();
}
inline ::google::protobuf::int32 GCUseHorseBack::useflag() const {
  // @@protoc_insertion_point(field_get:GCUseHorseBack.useflag)
  return useflag_;
}
inline void GCUseHorseBack::set_useflag(::google::protobuf::int32 value) {
  set_has_useflag();
  useflag_ = value;
  // @@protoc_insertion_point(field_set:GCUseHorseBack.useflag)
}

// optional int32 flag = 3;
inline bool GCUseHorseBack::has_flag() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GCUseHorseBack::set_has_flag() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GCUseHorseBack::clear_has_flag() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GCUseHorseBack::clear_flag() {
  flag_ = 0;
  clear_has_flag();
}
inline ::google::protobuf::int32 GCUseHorseBack::flag() const {
  // @@protoc_insertion_point(field_get:GCUseHorseBack.flag)
  return flag_;
}
inline void GCUseHorseBack::set_flag(::google::protobuf::int32 value) {
  set_has_flag();
  flag_ = value;
  // @@protoc_insertion_point(field_set:GCUseHorseBack.flag)
}

// -------------------------------------------------------------------

// CGCultureToUpStar

// optional int64 horseid = 1;
inline bool CGCultureToUpStar::has_horseid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CGCultureToUpStar::set_has_horseid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CGCultureToUpStar::clear_has_horseid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CGCultureToUpStar::clear_horseid() {
  horseid_ = GOOGLE_LONGLONG(0);
  clear_has_horseid();
}
inline ::google::protobuf::int64 CGCultureToUpStar::horseid() const {
  // @@protoc_insertion_point(field_get:CGCultureToUpStar.horseid)
  return horseid_;
}
inline void CGCultureToUpStar::set_horseid(::google::protobuf::int64 value) {
  set_has_horseid();
  horseid_ = value;
  // @@protoc_insertion_point(field_set:CGCultureToUpStar.horseid)
}

// optional int32 usegemflag = 2;
inline bool CGCultureToUpStar::has_usegemflag() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CGCultureToUpStar::set_has_usegemflag() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CGCultureToUpStar::clear_has_usegemflag() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CGCultureToUpStar::clear_usegemflag() {
  usegemflag_ = 0;
  clear_has_usegemflag();
}
inline ::google::protobuf::int32 CGCultureToUpStar::usegemflag() const {
  // @@protoc_insertion_point(field_get:CGCultureToUpStar.usegemflag)
  return usegemflag_;
}
inline void CGCultureToUpStar::set_usegemflag(::google::protobuf::int32 value) {
  set_has_usegemflag();
  usegemflag_ = value;
  // @@protoc_insertion_point(field_set:CGCultureToUpStar.usegemflag)
}

// -------------------------------------------------------------------

// GCCultureToUpStarBack

// optional int32 flag = 1;
inline bool GCCultureToUpStarBack::has_flag() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GCCultureToUpStarBack::set_has_flag() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GCCultureToUpStarBack::clear_has_flag() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GCCultureToUpStarBack::clear_flag() {
  flag_ = 0;
  clear_has_flag();
}
inline ::google::protobuf::int32 GCCultureToUpStarBack::flag() const {
  // @@protoc_insertion_point(field_get:GCCultureToUpStarBack.flag)
  return flag_;
}
inline void GCCultureToUpStarBack::set_flag(::google::protobuf::int32 value) {
  set_has_flag();
  flag_ = value;
  // @@protoc_insertion_point(field_set:GCCultureToUpStarBack.flag)
}

// optional int32 luckflag = 2;
inline bool GCCultureToUpStarBack::has_luckflag() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GCCultureToUpStarBack::set_has_luckflag() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GCCultureToUpStarBack::clear_has_luckflag() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GCCultureToUpStarBack::clear_luckflag() {
  luckflag_ = 0;
  clear_has_luckflag();
}
inline ::google::protobuf::int32 GCCultureToUpStarBack::luckflag() const {
  // @@protoc_insertion_point(field_get:GCCultureToUpStarBack.luckflag)
  return luckflag_;
}
inline void GCCultureToUpStarBack::set_luckflag(::google::protobuf::int32 value) {
  set_has_luckflag();
  luckflag_ = value;
  // @@protoc_insertion_point(field_set:GCCultureToUpStarBack.luckflag)
}

// optional .HorseInfo horseInfo = 3;
inline bool GCCultureToUpStarBack::has_horseinfo() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GCCultureToUpStarBack::set_has_horseinfo() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GCCultureToUpStarBack::clear_has_horseinfo() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GCCultureToUpStarBack::clear_horseinfo() {
  if (horseinfo_ != NULL) horseinfo_->::HorseInfo::Clear();
  clear_has_horseinfo();
}
inline const ::HorseInfo& GCCultureToUpStarBack::horseinfo() const {
  // @@protoc_insertion_point(field_get:GCCultureToUpStarBack.horseInfo)
  return horseinfo_ != NULL ? *horseinfo_ : *default_instance_->horseinfo_;
}
inline ::HorseInfo* GCCultureToUpStarBack::mutable_horseinfo() {
  set_has_horseinfo();
  if (horseinfo_ == NULL) horseinfo_ = new ::HorseInfo;
  // @@protoc_insertion_point(field_mutable:GCCultureToUpStarBack.horseInfo)
  return horseinfo_;
}
inline ::HorseInfo* GCCultureToUpStarBack::release_horseinfo() {
  clear_has_horseinfo();
  ::HorseInfo* temp = horseinfo_;
  horseinfo_ = NULL;
  return temp;
}
inline void GCCultureToUpStarBack::set_allocated_horseinfo(::HorseInfo* horseinfo) {
  delete horseinfo_;
  horseinfo_ = horseinfo;
  if (horseinfo) {
    set_has_horseinfo();
  } else {
    clear_has_horseinfo();
  }
  // @@protoc_insertion_point(field_set_allocated:GCCultureToUpStarBack.horseInfo)
}

// optional .HorseInfo newhorseInfo = 4;
inline bool GCCultureToUpStarBack::has_newhorseinfo() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GCCultureToUpStarBack::set_has_newhorseinfo() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GCCultureToUpStarBack::clear_has_newhorseinfo() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GCCultureToUpStarBack::clear_newhorseinfo() {
  if (newhorseinfo_ != NULL) newhorseinfo_->::HorseInfo::Clear();
  clear_has_newhorseinfo();
}
inline const ::HorseInfo& GCCultureToUpStarBack::newhorseinfo() const {
  // @@protoc_insertion_point(field_get:GCCultureToUpStarBack.newhorseInfo)
  return newhorseinfo_ != NULL ? *newhorseinfo_ : *default_instance_->newhorseinfo_;
}
inline ::HorseInfo* GCCultureToUpStarBack::mutable_newhorseinfo() {
  set_has_newhorseinfo();
  if (newhorseinfo_ == NULL) newhorseinfo_ = new ::HorseInfo;
  // @@protoc_insertion_point(field_mutable:GCCultureToUpStarBack.newhorseInfo)
  return newhorseinfo_;
}
inline ::HorseInfo* GCCultureToUpStarBack::release_newhorseinfo() {
  clear_has_newhorseinfo();
  ::HorseInfo* temp = newhorseinfo_;
  newhorseinfo_ = NULL;
  return temp;
}
inline void GCCultureToUpStarBack::set_allocated_newhorseinfo(::HorseInfo* newhorseinfo) {
  delete newhorseinfo_;
  newhorseinfo_ = newhorseinfo;
  if (newhorseinfo) {
    set_has_newhorseinfo();
  } else {
    clear_has_newhorseinfo();
  }
  // @@protoc_insertion_point(field_set_allocated:GCCultureToUpStarBack.newhorseInfo)
}

// -------------------------------------------------------------------

// CGLookHorse

// optional int64 playerUid = 1;
inline bool CGLookHorse::has_playeruid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CGLookHorse::set_has_playeruid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CGLookHorse::clear_has_playeruid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CGLookHorse::clear_playeruid() {
  playeruid_ = GOOGLE_LONGLONG(0);
  clear_has_playeruid();
}
inline ::google::protobuf::int64 CGLookHorse::playeruid() const {
  // @@protoc_insertion_point(field_get:CGLookHorse.playerUid)
  return playeruid_;
}
inline void CGLookHorse::set_playeruid(::google::protobuf::int64 value) {
  set_has_playeruid();
  playeruid_ = value;
  // @@protoc_insertion_point(field_set:CGLookHorse.playerUid)
}

// -------------------------------------------------------------------

// GCLookHorseBack

// optional int32 flag = 1;
inline bool GCLookHorseBack::has_flag() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GCLookHorseBack::set_has_flag() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GCLookHorseBack::clear_has_flag() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GCLookHorseBack::clear_flag() {
  flag_ = 0;
  clear_has_flag();
}
inline ::google::protobuf::int32 GCLookHorseBack::flag() const {
  // @@protoc_insertion_point(field_get:GCLookHorseBack.flag)
  return flag_;
}
inline void GCLookHorseBack::set_flag(::google::protobuf::int32 value) {
  set_has_flag();
  flag_ = value;
  // @@protoc_insertion_point(field_set:GCLookHorseBack.flag)
}

// optional int32 horseId = 2;
inline bool GCLookHorseBack::has_horseid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GCLookHorseBack::set_has_horseid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GCLookHorseBack::clear_has_horseid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GCLookHorseBack::clear_horseid() {
  horseid_ = 0;
  clear_has_horseid();
}
inline ::google::protobuf::int32 GCLookHorseBack::horseid() const {
  // @@protoc_insertion_point(field_get:GCLookHorseBack.horseId)
  return horseid_;
}
inline void GCLookHorseBack::set_horseid(::google::protobuf::int32 value) {
  set_has_horseid();
  horseid_ = value;
  // @@protoc_insertion_point(field_set:GCLookHorseBack.horseId)
}

// -------------------------------------------------------------------

// GCGetNewHorse

// optional int32 horseId = 1;
inline bool GCGetNewHorse::has_horseid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GCGetNewHorse::set_has_horseid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GCGetNewHorse::clear_has_horseid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GCGetNewHorse::clear_horseid() {
  horseid_ = 0;
  clear_has_horseid();
}
inline ::google::protobuf::int32 GCGetNewHorse::horseid() const {
  // @@protoc_insertion_point(field_get:GCGetNewHorse.horseId)
  return horseid_;
}
inline void GCGetNewHorse::set_horseid(::google::protobuf::int32 value) {
  set_has_horseid();
  horseid_ = value;
  // @@protoc_insertion_point(field_set:GCGetNewHorse.horseId)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_HorsesMessage_2eproto__INCLUDED
